<?php
/**
 * AddIntegrationToApplicationRequestErrorCodes
 *
 * PHP version 5
 *
 * @category Class
 * @package  Terapi\Client
 * @author   Terapi team
 * @link     https://github.com/terapi-integrations
 */

/**
 * Terapi.Web.Api-v1
 *
 * No description provided (generated by Terapi https://github.com/terapi-integrations)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/terapi-integrations.git
 * Terapi version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the Terapi code generator program.
 * https://github.com/terapi-integrations
 * Do not edit the class manually.
 */

namespace Terapi\Client\Model;
use \Terapi\Client\ObjectSerializer;

/**
 * AddIntegrationToApplicationRequestErrorCodes Class Doc Comment
 *
 * @category Class
 * @description 18999101 &#x3D; ApplicationNotFound  18999102 &#x3D; UnknownExceptionWhenCheckApplicationExistence  18999103 &#x3D; IntegrationNotFound  18999104 &#x3D; UnknownExceptionWhenCheckIntegrationExistence  18999105 &#x3D; UnknownExceptionWhenAddIntegrationToApplication  18999106 &#x3D; IntegrationAlreadyAddedToTheApplication  18999107 &#x3D; UnknownExceptionWhenCheckApplicationIntegrationUniqueness
 * @package  Terapi\Client
 * @author   Terapi team
 * @link     https://github.com/terapi-integrations
 */
class AddIntegrationToApplicationRequestErrorCodes
{
    /**
     * Possible values of this enum
     */
    const 18999101 = 18999101;
    const 18999102 = 18999102;
    const 18999103 = 18999103;
    const 18999104 = 18999104;
    const 18999105 = 18999105;
    const 18999106 = 18999106;
    const 18999107 = 18999107;
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::18999101
            self::18999102
            self::18999103
            self::18999104
            self::18999105
            self::18999106
            self::18999107
        ];
    }
}
