<?php
/**
 * ApplicationIntegrationListByApplicationIdRequestErrorCodes
 *
 * PHP version 5
 *
 * @category Class
 * @package  Terapi\Client
 * @author   Terapi team
 * @link     https://github.com/terapi-integrations
 */

/**
 * Terapi.Web.Api-v1
 *
 * No description provided (generated by Terapi https://github.com/terapi-integrations)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/terapi-integrations.git
 * Terapi version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the Terapi code generator program.
 * https://github.com/terapi-integrations
 * Do not edit the class manually.
 */

namespace Terapi\Client\Model;
use \Terapi\Client\ObjectSerializer;

/**
 * ApplicationIntegrationListByApplicationIdRequestErrorCodes Class Doc Comment
 *
 * @category Class
 * @description 18998 &#x3D; UnknownExceptionWhenTryingFetchApplicationIntegrations  18999 &#x3D; ApplicationNotFound
 * @package  Terapi\Client
 * @author   Terapi team
 * @link     https://github.com/terapi-integrations
 */
class ApplicationIntegrationListByApplicationIdRequestErrorCodes
{
    /**
     * Possible values of this enum
     */
    const 18998 = 18998;
    const 18999 = 18999;
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::18998
            self::18999
        ];
    }
}
