<?php
/**
 * CreateApplicationRequestErrorCodes
 *
 * PHP version 5
 *
 * @category Class
 * @package  Terapi\Client
 * @author   Terapi team
 * @link     https://github.com/terapi-integrations
 */

/**
 * Terapi.Web.Api-v1
 *
 * No description provided (generated by Terapi https://github.com/terapi-integrations)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/terapi-integrations.git
 * Terapi version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the Terapi code generator program.
 * https://github.com/terapi-integrations
 * Do not edit the class manually.
 */

namespace Terapi\Client\Model;
use \Terapi\Client\ObjectSerializer;

/**
 * CreateApplicationRequestErrorCodes Class Doc Comment
 *
 * @category Class
 * @description 15999101 &#x3D; ApplicationNameAlreadyExist  15999102 &#x3D; UnknownExceptionWhenValidateApplicationNameUniqueness  15999103 &#x3D; UnknownExceptionWhenInsertApplication  15999104 &#x3D; UserNotFound  15999105 &#x3D; UnknownExceptionWhenCreateOrganization
 * @package  Terapi\Client
 * @author   Terapi team
 * @link     https://github.com/terapi-integrations
 */
class CreateApplicationRequestErrorCodes
{
    /**
     * Possible values of this enum
     */
    const 15999101 = 15999101;
    const 15999102 = 15999102;
    const 15999103 = 15999103;
    const 15999104 = 15999104;
    const 15999105 = 15999105;
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::15999101
            self::15999102
            self::15999103
            self::15999104
            self::15999105
        ];
    }
}
