<?php
/**
 * CreateUserProfileRequestErrorCodes
 *
 * PHP version 5
 *
 * @category Class
 * @package  Terapi\Client
 * @author   Terapi team
 * @link     https://github.com/terapi-integrations
 */

/**
 * Terapi.Web.Api-v1
 *
 * No description provided (generated by Terapi https://github.com/terapi-integrations)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/terapi-integrations.git
 * Terapi version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the Terapi code generator program.
 * https://github.com/terapi-integrations
 * Do not edit the class manually.
 */

namespace Terapi\Client\Model;
use \Terapi\Client\ObjectSerializer;

/**
 * CreateUserProfileRequestErrorCodes Class Doc Comment
 *
 * @category Class
 * @description 14998101 &#x3D; UnknownExceptionWhenFetchJwtUserProfile  14998102 &#x3D; UnknownExceptionWhenCreateUserProfile  14998103 &#x3D; IncorrectDataInUserJwtPayload  14998104 &#x3D; UnknownExceptionWhenSubscribeUserToFreePlan  14998105 &#x3D; UserAlreadyExistInDataStorage  14998106 &#x3D; UnknownExceptionWhenCheckUserExistence
 * @package  Terapi\Client
 * @author   Terapi team
 * @link     https://github.com/terapi-integrations
 */
class CreateUserProfileRequestErrorCodes
{
    /**
     * Possible values of this enum
     */
    const 14998101 = 14998101;
    const 14998102 = 14998102;
    const 14998103 = 14998103;
    const 14998104 = 14998104;
    const 14998105 = 14998105;
    const 14998106 = 14998106;
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::14998101
            self::14998102
            self::14998103
            self::14998104
            self::14998105
            self::14998106
        ];
    }
}
