<?php
/**
 * DeclineTenantInvitationRequestErrorCodes
 *
 * PHP version 5
 *
 * @category Class
 * @package  Terapi\Client
 * @author   Terapi team
 * @link     https://github.com/terapi-integrations
 */

/**
 * Terapi.Web.Api-v1
 *
 * No description provided (generated by Terapi https://github.com/terapi-integrations)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/terapi-integrations.git
 * Terapi version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the Terapi code generator program.
 * https://github.com/terapi-integrations
 * Do not edit the class manually.
 */

namespace Terapi\Client\Model;
use \Terapi\Client\ObjectSerializer;

/**
 * DeclineTenantInvitationRequestErrorCodes Class Doc Comment
 *
 * @category Class
 * @description 20996101 &#x3D; TenantNotFound  20996102 &#x3D; UnknownExceptionWhileFetchingTenant  20996103 &#x3D; UnknownExceptionWhileDecliningTenant  20996104 &#x3D; TenantIsNotInInvitedStatus  20996105 &#x3D; UnknownExceptionWhileCheckingIfTenantIsInCorrectStatus
 * @package  Terapi\Client
 * @author   Terapi team
 * @link     https://github.com/terapi-integrations
 */
class DeclineTenantInvitationRequestErrorCodes
{
    /**
     * Possible values of this enum
     */
    const 20996101 = 20996101;
    const 20996102 = 20996102;
    const 20996103 = 20996103;
    const 20996104 = 20996104;
    const 20996105 = 20996105;
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::20996101
            self::20996102
            self::20996103
            self::20996104
            self::20996105
        ];
    }
}
