<?php
/**
 * DeleteApplicationRequestErrorCodes
 *
 * PHP version 5
 *
 * @category Class
 * @package  Terapi\Client
 * @author   Terapi team
 * @link     https://github.com/terapi-integrations
 */

/**
 * Terapi.Web.Api-v1
 *
 * No description provided (generated by Terapi https://github.com/terapi-integrations)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/terapi-integrations.git
 * Terapi version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the Terapi code generator program.
 * https://github.com/terapi-integrations
 * Do not edit the class manually.
 */

namespace Terapi\Client\Model;
use \Terapi\Client\ObjectSerializer;

/**
 * DeleteApplicationRequestErrorCodes Class Doc Comment
 *
 * @category Class
 * @description 15997101 &#x3D; ApplicationNotFound  15997102 &#x3D; UnknownExceptionWhenFetchApplicationExistence  15997103 &#x3D; UnknownExceptionWhenDeleteApplication
 * @package  Terapi\Client
 * @author   Terapi team
 * @link     https://github.com/terapi-integrations
 */
class DeleteApplicationRequestErrorCodes
{
    /**
     * Possible values of this enum
     */
    const 15997101 = 15997101;
    const 15997102 = 15997102;
    const 15997103 = 15997103;
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::15997101
            self::15997102
            self::15997103
        ];
    }
}
