<?php
/**
 * InviteTenantRequestErrorCodes
 *
 * PHP version 5
 *
 * @category Class
 * @package  Terapi\Client
 * @author   Terapi team
 * @link     https://github.com/terapi-integrations
 */

/**
 * Terapi.Web.Api-v1
 *
 * No description provided (generated by Terapi https://github.com/terapi-integrations)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/terapi-integrations.git
 * Terapi version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the Terapi code generator program.
 * https://github.com/terapi-integrations
 * Do not edit the class manually.
 */

namespace Terapi\Client\Model;
use \Terapi\Client\ObjectSerializer;

/**
 * InviteTenantRequestErrorCodes Class Doc Comment
 *
 * @category Class
 * @description 20998101 &#x3D; ApplicationIntegrationNotFound  20998102 &#x3D; UnknownExceptionWhenCheckApplicationExistence  20998103 &#x3D; UnknownExceptionWhenCreateTenant  20998104 &#x3D; UnknownExceptionWhenSendingEmailToInvitedEmailAddress  20998105 &#x3D; UserNotFound  20998106 &#x3D; UnknownExceptionWhenInsertApplication  20998107 &#x3D; UnknownExceptionWhenCreateUserTenant  20998108 &#x3D; UnknownExceptionWhenCreatingEmailContent  20998109 &#x3D; UnknownExceptionWhenCreatingEmailAcceptInvitationUrl  20998110 &#x3D; UnknownExceptionWhenAddingTenantInKeycloak  20998111 &#x3D; UnknownExceptionWhenAddingTenantInOrganization  20998112 &#x3D; UnknownExceptionWhenCreateTenantUser
 * @package  Terapi\Client
 * @author   Terapi team
 * @link     https://github.com/terapi-integrations
 */
class InviteTenantRequestErrorCodes
{
    /**
     * Possible values of this enum
     */
    const 20998101 = 20998101;
    const 20998102 = 20998102;
    const 20998103 = 20998103;
    const 20998104 = 20998104;
    const 20998105 = 20998105;
    const 20998106 = 20998106;
    const 20998107 = 20998107;
    const 20998108 = 20998108;
    const 20998109 = 20998109;
    const 20998110 = 20998110;
    const 20998111 = 20998111;
    const 20998112 = 20998112;
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::20998101
            self::20998102
            self::20998103
            self::20998104
            self::20998105
            self::20998106
            self::20998107
            self::20998108
            self::20998109
            self::20998110
            self::20998111
            self::20998112
        ];
    }
}
