<?php
/**
 * RevokeApplicationApiKeyRequestErrorCodes
 *
 * PHP version 5
 *
 * @category Class
 * @package  Terapi\Client
 * @author   Terapi team
 * @link     https://github.com/terapi-integrations
 */

/**
 * Terapi.Web.Api-v1
 *
 * No description provided (generated by Terapi https://github.com/terapi-integrations)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/terapi-integrations.git
 * Terapi version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the Terapi code generator program.
 * https://github.com/terapi-integrations
 * Do not edit the class manually.
 */

namespace Terapi\Client\Model;
use \Terapi\Client\ObjectSerializer;

/**
 * RevokeApplicationApiKeyRequestErrorCodes Class Doc Comment
 *
 * @category Class
 * @description 16998101 &#x3D; ApplicationApiKeyNotFound  16998102 &#x3D; UnknownExceptionWhenCheckApplicationExistence  16998103 &#x3D; UnknownExceptionWhenGenerateApplicationApiKey
 * @package  Terapi\Client
 * @author   Terapi team
 * @link     https://github.com/terapi-integrations
 */
class RevokeApplicationApiKeyRequestErrorCodes
{
    /**
     * Possible values of this enum
     */
    const 16998101 = 16998101;
    const 16998102 = 16998102;
    const 16998103 = 16998103;
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::16998101
            self::16998102
            self::16998103
        ];
    }
}
