<?php
/**
 * UpdateApplicationRequestErrorCodes
 *
 * PHP version 5
 *
 * @category Class
 * @package  Terapi\Client
 * @author   Terapi team
 * @link     https://github.com/terapi-integrations
 */

/**
 * Terapi.Web.Api-v1
 *
 * No description provided (generated by Terapi https://github.com/terapi-integrations)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/terapi-integrations.git
 * Terapi version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the Terapi code generator program.
 * https://github.com/terapi-integrations
 * Do not edit the class manually.
 */

namespace Terapi\Client\Model;
use \Terapi\Client\ObjectSerializer;

/**
 * UpdateApplicationRequestErrorCodes Class Doc Comment
 *
 * @category Class
 * @description 15998101 &#x3D; ApplicationNotFound  15998102 &#x3D; UnknownExceptionWhenFetchApplication  15998103 &#x3D; UnknownExceptionWhenInsertApplication
 * @package  Terapi\Client
 * @author   Terapi team
 * @link     https://github.com/terapi-integrations
 */
class UpdateApplicationRequestErrorCodes
{
    /**
     * Possible values of this enum
     */
    const 15998101 = 15998101;
    const 15998102 = 15998102;
    const 15998103 = 15998103;
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::15998101
            self::15998102
            self::15998103
        ];
    }
}
