<?php
/**
 * UpdateTenantConnectionRequestErrorCodes
 *
 * PHP version 5
 *
 * @category Class
 * @package  Terapi\Client
 * @author   Terapi team
 * @link     https://github.com/terapi-integrations
 */

/**
 * Terapi.Web.Api-v1
 *
 * No description provided (generated by Terapi https://github.com/terapi-integrations)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/terapi-integrations.git
 * Terapi version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the Terapi code generator program.
 * https://github.com/terapi-integrations
 * Do not edit the class manually.
 */

namespace Terapi\Client\Model;
use \Terapi\Client\ObjectSerializer;

/**
 * UpdateTenantConnectionRequestErrorCodes Class Doc Comment
 *
 * @category Class
 * @description 20997101 &#x3D; TenantNotFound  20997102 &#x3D; UnknownExceptionWhenCheckTenantExistence  20997103 &#x3D; UnknownExceptionWhenUpdateTenantConnection
 * @package  Terapi\Client
 * @author   Terapi team
 * @link     https://github.com/terapi-integrations
 */
class UpdateTenantConnectionRequestErrorCodes
{
    /**
     * Possible values of this enum
     */
    const 20997101 = 20997101;
    const 20997102 = 20997102;
    const 20997103 = 20997103;
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::20997101
            self::20997102
            self::20997103
        ];
    }
}
