<?php
/**
 * UserApplicationListRequestErrorCodes
 *
 * PHP version 5
 *
 * @category Class
 * @package  Terapi\Client
 * @author   Terapi team
 * @link     https://github.com/terapi-integrations
 */

/**
 * Terapi.Web.Api-v1
 *
 * No description provided (generated by Terapi https://github.com/terapi-integrations)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/terapi-integrations.git
 * Terapi version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the Terapi code generator program.
 * https://github.com/terapi-integrations
 * Do not edit the class manually.
 */

namespace Terapi\Client\Model;
use \Terapi\Client\ObjectSerializer;

/**
 * UserApplicationListRequestErrorCodes Class Doc Comment
 *
 * @category Class
 * @description 15996101 &#x3D; UnknownExceptionWhenTryingFetchApplications  15996102 &#x3D; UserNotFound  15996103 &#x3D; UnknownExceptionWhenInsertApplication
 * @package  Terapi\Client
 * @author   Terapi team
 * @link     https://github.com/terapi-integrations
 */
class UserApplicationListRequestErrorCodes
{
    /**
     * Possible values of this enum
     */
    const 15996101 = 15996101;
    const 15996102 = 15996102;
    const 15996103 = 15996103;
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::15996101
            self::15996102
            self::15996103
        ];
    }
}
