<?php
/**
 * UserProfileStatisticsErrorCodes
 *
 * PHP version 5
 *
 * @category Class
 * @package  Terapi\Client
 * @author   Terapi team
 * @link     https://github.com/terapi-integrations
 */

/**
 * Terapi.Web.Api-v1
 *
 * No description provided (generated by Terapi https://github.com/terapi-integrations)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/terapi-integrations.git
 * Terapi version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the Terapi code generator program.
 * https://github.com/terapi-integrations
 * Do not edit the class manually.
 */

namespace Terapi\Client\Model;
use \Terapi\Client\ObjectSerializer;

/**
 * UserProfileStatisticsErrorCodes Class Doc Comment
 *
 * @category Class
 * @description 14997101 &#x3D; UserNotFound  14997102 &#x3D; UserDoesNotHaveActiveSubscription  14997103 &#x3D; UnknownExceptionWhenFetchUserProfileStatistics
 * @package  Terapi\Client
 * @author   Terapi team
 * @link     https://github.com/terapi-integrations
 */
class UserProfileStatisticsErrorCodes
{
    /**
     * Possible values of this enum
     */
    const 14997101 = 14997101;
    const 14997102 = 14997102;
    const 14997103 = 14997103;
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::14997101
            self::14997102
            self::14997103
        ];
    }
}
